import { cn } from "@/lib/utils";

/**
 * Inline-country SVG flag, served as a static asset from /flags/<CODE>.svg
 * (generated by scripts/generate-currency-data.mjs). Flags are only rendered
 * when the parent dropdown is open, and load lazily as the list scrolls.
 */
export function CountryFlag({
  code,
  className,
}: {
  code: string;
  className?: string;
}) {
  if (!code) return null;
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static vendored SVG assets
    <img
      src={`/flags/${code}.svg`}
      alt=""
      aria-hidden="true"
      loading="lazy"
      decoding="async"
      className={cn(
        "h-3.5 w-[21px] shrink-0 rounded-[2px] object-cover shadow-[0_0_0_1px_rgba(0,0,0,0.06)]",
        className,
      )}
    />
  );
}
